version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
  api:  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres:5432/simple_bank?sslmode=disable 
    depends_on:
      postgres:
        condition: service_healthy
    # If using entrypoint here, the CMD command at Dockerfile will be ignored
    # entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    # command: [ "/app/main" ]
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
